main: com.eyeofmidas.skyblock.SkyblockGenerator
name: SkyblockGenerator
version: 0.2
author: Justin Gilman
website: http://eyeofmidas.com/skyblock
description: SkyblockGenerator is a map generator that creates chunks inspired by Skyblock.
load: startup
